description: "The lean, default runtime for the cx-server and basic flows. Contains only essential packages."
tools:
  python:
    packages:
      - "cx-core-schemas @ git+https://github.com/syncropel/cx-core-schemas.git@v0.2.6"
      - "fastapi>=0.110.0"
      - "uvicorn[standard]>=0.29.0"
      - "pydantic>=2.0,<3.0"
      - "structlog>=24.1.0"
      - "rich>=13.0.0"
      - "pyyaml>=6.0"
      - "jinja2>=3.1.0"
      - "httpx[http2]>=0.25.0"
      - "python-dotenv>=1.0.0"
      - "lark>=1.1.9"
      - "markdown>=3.6"
  system:
    packages:
      - "nixpkgs#python312"
      - "nixpkgs#git"
      - "nixpkgs#unixodbc"
